version: "3"

services:
  wordpress:
    image: "wordpress:latest"
    environment:
      VIRTUAL_HOST: "${DOCKER_DEV_DOMAIN:-lsdcommerce.local}"
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_USER: "root"
      WORDPRESS_CONFIG_EXTRA: |
        define( 'ALTERNATE_WP_CRON', true);
        define( 'WP_DEBUG', true);
        define( 'WP_DEBUG_LOG', 'wp-content/plugins/lsdcommerce/debug.log');
        define( 'WP_DEBUG_DISPLAY', true );
        define( 'FS_METHOD', 'direct');
        define( 'WP_MEMORY_LIMIT', '512M');
        define( 'WP_HOME', 'https://lsdcommerce.local' );
        define( 'WP_SITEURL', 'https://lsdcommerce.local' );
        define( 'WP_HTTP_BLOCK_EXTERNAL', false );
        define( 'WP_ACCESSIBLE_HOSTS', 'api.wordpress.org,*.github.com' );
    extra_hosts:
      - "api.wordpress.org:66.155.40.202"
    depends_on:
      - "mysql"
    networks:
      - "forntend"
      - "backend"
    volumes:
      - "wp:/var/www/html:rw"
      - "./wp-plugins:/var/www/html/wp-content/plugins:rw"
      - "./wp-themes:/var/www/html/wp-content/themes:rw"
      - "./wp-content:/var/www/html/wp-content:rw"
      - ".:/var/www/html/wp-content/plugins/lsdcommerce:rw"
  wp-cli:
    image: "wordpress:cli-${WP_CLI_VERSION:-2.2.0}-php${PHP_VERSION:-7.3}"
    environment:
      - APACHE_RUN_USER="www-data"
      - APACHE_RUN_GROUP="www-data"
    depends_on:
      - "mysql"
    networks:
      - "backend"
    volumes:
      - "wp:/var/www/html:rw"
      - "./bin/install-wp.sh:/usr/local/bin/install-wp:rw"
      - "./wp-plugins:/var/www/html/wp-content/plugins:rw"
      - "./wp-themes:/var/www/html/wp-content/themes:rw"
      - "./wp-content:/var/www/html/wp-content:rw"
      - ".:/var/www/html/wp-content/plugins/lsdcommerce:rw"
  mysql:
    image: "mariadb:10.2"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - "backend"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ""
    depends_on:
      - "mysql"
    networks:
      - "backend"
    ports:
      - "8888:80"
  proxy:
    image: "jwilder/nginx-proxy:alpine"
    ports:
      - "80:80"
    networks:
      forntend:
        aliases:
          - "${DOCKER_DEV_DOMAIN:-lsdcommerce.local}"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

networks:
  forntend: {}
  backend: {}

volumes:
  wp: {}
